name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cashapp/activate-hermit@v1

      - uses: ./
        id: make-version
        with:
          package: make

      - if: steps.make-version.outputs.version != '4.4'
        run: |
          echo "Actual version: ${{ steps.make-version.outputs.version }}"
          exit 1

      - uses: ./
        id: hermit-version
        with:
          package: hermit
        continue-on-error: true

      - if: steps.hermit-version.outcome != 'failure'
        run: |
          echo "Actual outcome: ${{ steps.hermit-version.outcome }}"
          exit 1

      - uses: ./
        id: bash-version
        with:
          package: bash
        continue-on-error: true

      - if: steps.bash-version.outcome != 'failure'
        run: |
          echo "Actual outcome: ${{ steps.bash-version.outcome }}"
          exit 1